"""keqingrl interactive policy family."""

from keqingrl.actions import (
    ACTION_FLAG_REACH,
    ACTION_FLAG_TSUMOGIRI,
    ActionSpec,
    ActionType,
    action_from_mahjong_spec,
    action_from_mjai,
    bind_reach_discard,
    decode_action_id,
    encode_action_id,
)
from keqingrl.contracts import ActionSample, ObsTensorBatch, PolicyInput, PolicyOutput
from keqingrl.distribution import MaskedCategorical
from keqingrl.buffer import PPOBatch, build_ppo_batch, compute_returns_and_advantages, stack_obs_batches
from keqingrl.env import DiscardOnlyMahjongEnv, EnvState, StepResult
from keqingrl.opponent_pool import (
    OpponentPool,
    OpponentPoolEntry,
    SeatPolicyAssignment,
    build_selfplay_seat_assignments,
)
from keqingrl.policy import InteractivePolicy, NeuralInteractivePolicy, RandomInteractivePolicy
from keqingrl.ppo import PPOLossBreakdown, compute_ppo_loss, ppo_update
from keqingrl.review import (
    EpisodeReview,
    ReviewCandidate,
    StepReview,
    build_policy_resolver,
    export_episode_review_jsonl,
    format_action_spec,
    review_rollout_episode,
    review_rollout_step,
)
from keqingrl.rewards import (
    DEFAULT_PT_MAP,
    RULE_CONTEXT_DIM,
    build_rule_context,
    normalize_pt_map,
    pt_map_scale,
    terminal_rank_rewards,
)
from keqingrl.rollout import (
    RolloutEpisode,
    RolloutStep,
    backfill_actor_terminal_rewards,
    backfill_terminal_rewards,
)
from keqingrl.selfplay import (
    DiscardOnlyIterationMetrics,
    DiscardOnlyIterationResult,
    build_episode_ppo_batch,
    build_episodes_ppo_batch,
    collect_discard_only_episode,
    collect_discard_only_episodes,
    collect_policy_episode,
    collect_policy_episodes,
    collect_selfplay_episode,
    collect_selfplay_episodes,
    run_ppo_iteration,
    run_discard_only_ppo_iteration,
    summarize_iteration,
    summarize_discard_only_iteration,
)
from keqingrl.training import (
    DiscardOnlyEvalMetrics,
    DiscardOnlyTrainingHistory,
    DiscardOnlyTrainingIteration,
    evaluate_discard_only_policy,
    evaluate_policy,
    run_discard_only_training,
    run_training,
)

__all__ = [
    "ACTION_FLAG_REACH",
    "ACTION_FLAG_TSUMOGIRI",
    "ActionSample",
    "ActionSpec",
    "ActionType",
    "DEFAULT_PT_MAP",
    "DiscardOnlyMahjongEnv",
    "DiscardOnlyEvalMetrics",
    "DiscardOnlyIterationMetrics",
    "DiscardOnlyIterationResult",
    "DiscardOnlyTrainingHistory",
    "DiscardOnlyTrainingIteration",
    "EpisodeReview",
    "EnvState",
    "InteractivePolicy",
    "MaskedCategorical",
    "NeuralInteractivePolicy",
    "ObsTensorBatch",
    "OpponentPool",
    "OpponentPoolEntry",
    "PPOBatch",
    "PPOLossBreakdown",
    "PolicyInput",
    "PolicyOutput",
    "RandomInteractivePolicy",
    "ReviewCandidate",
    "RULE_CONTEXT_DIM",
    "RolloutEpisode",
    "RolloutStep",
    "SeatPolicyAssignment",
    "StepReview",
    "StepResult",
    "action_from_mahjong_spec",
    "action_from_mjai",
    "backfill_actor_terminal_rewards",
    "backfill_terminal_rewards",
    "bind_reach_discard",
    "build_episode_ppo_batch",
    "build_episodes_ppo_batch",
    "build_policy_resolver",
    "build_rule_context",
    "build_ppo_batch",
    "collect_discard_only_episode",
    "collect_discard_only_episodes",
    "collect_policy_episode",
    "collect_policy_episodes",
    "collect_selfplay_episode",
    "collect_selfplay_episodes",
    "compute_ppo_loss",
    "compute_returns_and_advantages",
    "decode_action_id",
    "encode_action_id",
    "evaluate_discard_only_policy",
    "evaluate_policy",
    "export_episode_review_jsonl",
    "format_action_spec",
    "normalize_pt_map",
    "ppo_update",
    "pt_map_scale",
    "review_rollout_episode",
    "review_rollout_step",
    "run_ppo_iteration",
    "run_discard_only_ppo_iteration",
    "run_discard_only_training",
    "run_training",
    "stack_obs_batches",
    "build_selfplay_seat_assignments",
    "summarize_iteration",
    "summarize_discard_only_iteration",
    "terminal_rank_rewards",
]
