"""keqingrl interactive policy family."""

from keqingrl.actions import (
    ACTION_FLAG_REACH,
    ACTION_FLAG_TSUMOGIRI,
    ActionSpec,
    ActionType,
    action_from_mahjong_spec,
    action_from_mjai,
    bind_reach_discard,
    decode_action_id,
    encode_action_id,
    make_action_canonical_key,
)
from keqingrl.contracts import ActionSample, ObsTensorBatch, PolicyInput, PolicyOutput
from keqingrl.distribution import MaskedCategorical
from keqingrl.buffer import PPOBatch, build_ppo_batch, compute_returns_and_advantages, stack_obs_batches
from keqingrl.env import DiscardOnlyMahjongEnv, EnvState, StepResult
from keqingrl.latency import LatencyReport, measure_latency_smoke
from keqingrl.opponent_pool import (
    OpponentPool,
    OpponentPoolEntry,
    SeatPolicyAssignment,
    build_selfplay_seat_assignments,
)
from keqingrl.metadata import (
    ACTION_CONTRACT_VERSION,
    ACTION_FEATURE_CONTRACT_VERSION,
    ENV_CONTRACT_VERSION,
    MODEL_FAMILY,
    OBSERVATION_CONTRACT_VERSION,
    POLICY_CONTRACT_VERSION,
    REWARD_SPEC_VERSION as METADATA_REWARD_SPEC_VERSION,
    RULE_CONTEXT_ENCODING_VERSION as METADATA_RULE_CONTEXT_ENCODING_VERSION,
    RULE_SCORE_VERSION,
    STYLE_CONTEXT_DIM as METADATA_STYLE_CONTEXT_DIM,
    STYLE_CONTEXT_VERSION as METADATA_STYLE_CONTEXT_VERSION,
    default_checkpoint_metadata,
    validate_checkpoint_metadata,
)
from keqingrl.policy import (
    InteractivePolicy,
    NeuralInteractivePolicy,
    RandomInteractivePolicy,
    RulePriorDeltaPolicy,
    RulePriorPolicy,
)
from keqingrl.ppo import (
    CriticPretrainLossBreakdown,
    PPOLossBreakdown,
    compute_critic_pretrain_loss,
    compute_ppo_loss,
    critic_pretrain_update,
    ppo_update,
)
from keqingrl.review import (
    EpisodeReview,
    ReviewCandidate,
    StepReview,
    build_policy_resolver,
    export_episode_review_jsonl,
    format_action_spec,
    review_rollout_episode,
    review_rollout_step,
)
from keqingrl.rewards import (
    DEFAULT_PT_MAP,
    DEFAULT_REWARD_SPEC,
    DEFAULT_RULE_CONTEXT,
    RULE_CONTEXT_DIM,
    RULE_CONTEXT_ENCODING_VERSION,
    REWARD_SPEC_VERSION,
    RewardSpec,
    RuleContext,
    build_rule_context,
    normalize_pt_map,
    pt_map_scale,
    terminal_rank_rewards,
)
from keqingrl.rule_score import (
    DEFAULT_RULE_SCORE_CONFIG,
    RuleScoreConfig,
    RuleScoreEntry,
    RuleScoreResult,
    prior_logits_from_raw_scores,
    score_legal_actions,
    smoothed_prior_probs,
)
from keqingrl.rollout import (
    RolloutEpisode,
    RolloutStep,
    backfill_actor_terminal_rewards,
    backfill_terminal_rewards,
)
from keqingrl.style import (
    DEFAULT_STYLE_CONTEXT,
    STYLE_CONTEXT_DIM,
    STYLE_CONTEXT_VERSION,
    StyleContext,
    build_style_context,
)
from keqingrl.selfplay import (
    DiscardOnlyIterationMetrics,
    DiscardOnlyIterationResult,
    build_episode_ppo_batch,
    build_episodes_ppo_batch,
    collect_discard_only_episode,
    collect_discard_only_episodes,
    collect_policy_episode,
    collect_policy_episodes,
    collect_selfplay_episode,
    collect_selfplay_episodes,
    run_ppo_iteration,
    run_discard_only_ppo_iteration,
    summarize_iteration,
    summarize_discard_only_iteration,
)
from keqingrl.training import (
    CriticPretrainingIterationResult,
    DiscardOnlyEvalMetrics,
    DiscardOnlyTrainingHistory,
    DiscardOnlyTrainingIteration,
    FixedSeedEvaluationSmoke,
    evaluate_discard_only_policy,
    evaluate_policy,
    run_fixed_seed_evaluation_smoke,
    run_critic_pretraining_iteration,
    run_discard_only_training,
    run_training,
)

__all__ = [
    "ACTION_FLAG_REACH",
    "ACTION_FLAG_TSUMOGIRI",
    "ActionSample",
    "ActionSpec",
    "ActionType",
    "ACTION_CONTRACT_VERSION",
    "CriticPretrainLossBreakdown",
    "CriticPretrainingIterationResult",
    "DEFAULT_PT_MAP",
    "DEFAULT_REWARD_SPEC",
    "DEFAULT_RULE_CONTEXT",
    "DEFAULT_RULE_SCORE_CONFIG",
    "DEFAULT_STYLE_CONTEXT",
    "DiscardOnlyMahjongEnv",
    "DiscardOnlyEvalMetrics",
    "DiscardOnlyIterationMetrics",
    "DiscardOnlyIterationResult",
    "DiscardOnlyTrainingHistory",
    "DiscardOnlyTrainingIteration",
    "EpisodeReview",
    "EnvState",
    "FixedSeedEvaluationSmoke",
    "InteractivePolicy",
    "LatencyReport",
    "MaskedCategorical",
    "METADATA_RULE_CONTEXT_ENCODING_VERSION",
    "METADATA_REWARD_SPEC_VERSION",
    "METADATA_STYLE_CONTEXT_DIM",
    "METADATA_STYLE_CONTEXT_VERSION",
    "MODEL_FAMILY",
    "NeuralInteractivePolicy",
    "ObsTensorBatch",
    "OBSERVATION_CONTRACT_VERSION",
    "OpponentPool",
    "OpponentPoolEntry",
    "PPOBatch",
    "PPOLossBreakdown",
    "PolicyInput",
    "PolicyOutput",
    "POLICY_CONTRACT_VERSION",
    "RandomInteractivePolicy",
    "RewardSpec",
    "ReviewCandidate",
    "RULE_CONTEXT_DIM",
    "RULE_CONTEXT_ENCODING_VERSION",
    "REWARD_SPEC_VERSION",
    "RULE_SCORE_VERSION",
    "RuleContext",
    "RulePriorDeltaPolicy",
    "RulePriorPolicy",
    "RuleScoreConfig",
    "RuleScoreEntry",
    "RuleScoreResult",
    "RolloutEpisode",
    "RolloutStep",
    "SeatPolicyAssignment",
    "StepReview",
    "StepResult",
    "STYLE_CONTEXT_DIM",
    "STYLE_CONTEXT_VERSION",
    "StyleContext",
    "action_from_mahjong_spec",
    "action_from_mjai",
    "backfill_actor_terminal_rewards",
    "backfill_terminal_rewards",
    "bind_reach_discard",
    "build_episode_ppo_batch",
    "build_episodes_ppo_batch",
    "build_policy_resolver",
    "build_rule_context",
    "build_style_context",
    "build_ppo_batch",
    "default_checkpoint_metadata",
    "collect_discard_only_episode",
    "collect_discard_only_episodes",
    "collect_policy_episode",
    "collect_policy_episodes",
    "collect_selfplay_episode",
    "collect_selfplay_episodes",
    "compute_ppo_loss",
    "compute_critic_pretrain_loss",
    "compute_returns_and_advantages",
    "critic_pretrain_update",
    "decode_action_id",
    "encode_action_id",
    "evaluate_discard_only_policy",
    "evaluate_policy",
    "export_episode_review_jsonl",
    "format_action_spec",
    "make_action_canonical_key",
    "measure_latency_smoke",
    "normalize_pt_map",
    "ppo_update",
    "prior_logits_from_raw_scores",
    "pt_map_scale",
    "review_rollout_episode",
    "review_rollout_step",
    "run_ppo_iteration",
    "run_discard_only_ppo_iteration",
    "run_discard_only_training",
    "run_critic_pretraining_iteration",
    "run_fixed_seed_evaluation_smoke",
    "run_training",
    "score_legal_actions",
    "smoothed_prior_probs",
    "stack_obs_batches",
    "build_selfplay_seat_assignments",
    "summarize_iteration",
    "summarize_discard_only_iteration",
    "terminal_rank_rewards",
    "validate_checkpoint_metadata",
]
