"""Xmodel1 schema constants and field definitions.

This module mirrors the documented field-level protocol in
`docs/xmodel1_schema_spec.md` and is the Python-side single source of truth for
loader/model shape expectations.
"""

from __future__ import annotations

from training.cache_schema import (
    XMODEL1_AUX_TARGET_FIELDS,
    XMODEL1_BASE_FIELDS,
    XMODEL1_CANDIDATE_FEATURE_DIM,
    XMODEL1_CANDIDATE_FLAG_DIM,
    XMODEL1_MAX_CANDIDATES,
    XMODEL1_MAX_SPECIAL_CANDIDATES,
    XMODEL1_METADATA_FIELDS,
    XMODEL1_SCHEMA_NAME,
    XMODEL1_SCHEMA_VERSION,
    XMODEL1_SPECIAL_CANDIDATE_FEATURE_DIM,
    XMODEL1_SPECIAL_FIELDS,
    XMODEL1_TEACHER_FIELDS,
)

XMODEL1_DISCARD_REQUIRED_FIELDS = (
    *XMODEL1_BASE_FIELDS,
    *XMODEL1_TEACHER_FIELDS,
    *XMODEL1_AUX_TARGET_FIELDS,
    *XMODEL1_METADATA_FIELDS,
    *XMODEL1_SPECIAL_FIELDS,
)

XMODEL1_SAMPLE_TYPE_DISCARD = 0
XMODEL1_SAMPLE_TYPE_RIICHI = 1
XMODEL1_SAMPLE_TYPE_CALL = 2
XMODEL1_SAMPLE_TYPE_HORA = 3

XMODEL1_SPECIAL_TYPE_REACH = 0
XMODEL1_SPECIAL_TYPE_DAMA = 1
XMODEL1_SPECIAL_TYPE_HORA = 2
XMODEL1_SPECIAL_TYPE_CHI_LOW = 3
XMODEL1_SPECIAL_TYPE_CHI_MID = 4
XMODEL1_SPECIAL_TYPE_CHI_HIGH = 5
XMODEL1_SPECIAL_TYPE_PON = 6
XMODEL1_SPECIAL_TYPE_DAIMINKAN = 7
XMODEL1_SPECIAL_TYPE_ANKAN = 8
XMODEL1_SPECIAL_TYPE_KAKAN = 9
XMODEL1_SPECIAL_TYPE_RYUKYOKU = 10
XMODEL1_SPECIAL_TYPE_NONE = 11

XMODEL1_CHI_SPECIAL_TYPES = (
    XMODEL1_SPECIAL_TYPE_CHI_LOW,
    XMODEL1_SPECIAL_TYPE_CHI_MID,
    XMODEL1_SPECIAL_TYPE_CHI_HIGH,
)

XMODEL1_SPECIAL_TYPE_CHI = XMODEL1_SPECIAL_TYPE_CHI_LOW

XMODEL1_KAN_SPECIAL_TYPES = (
    XMODEL1_SPECIAL_TYPE_DAIMINKAN,
    XMODEL1_SPECIAL_TYPE_ANKAN,
    XMODEL1_SPECIAL_TYPE_KAKAN,
)

XMODEL1_SPECIAL_TYPE_KAN = XMODEL1_SPECIAL_TYPE_DAIMINKAN

XMODEL1_SPECIAL_TYPE_NAMES = (
    "reach",
    "dama",
    "hora",
    "chi_low",
    "chi_mid",
    "chi_high",
    "pon",
    "daiminkan",
    "ankan",
    "kakan",
    "ryukyoku",
    "none",
)

__all__ = [
    "XMODEL1_SCHEMA_NAME",
    "XMODEL1_SCHEMA_VERSION",
    "XMODEL1_MAX_CANDIDATES",
    "XMODEL1_CANDIDATE_FEATURE_DIM",
    "XMODEL1_CANDIDATE_FLAG_DIM",
    "XMODEL1_MAX_SPECIAL_CANDIDATES",
    "XMODEL1_SPECIAL_CANDIDATE_FEATURE_DIM",
    "XMODEL1_DISCARD_REQUIRED_FIELDS",
    "XMODEL1_SPECIAL_FIELDS",
    "XMODEL1_SAMPLE_TYPE_DISCARD",
    "XMODEL1_SAMPLE_TYPE_RIICHI",
    "XMODEL1_SAMPLE_TYPE_CALL",
    "XMODEL1_SAMPLE_TYPE_HORA",
    "XMODEL1_SPECIAL_TYPE_REACH",
    "XMODEL1_SPECIAL_TYPE_DAMA",
    "XMODEL1_SPECIAL_TYPE_HORA",
    "XMODEL1_SPECIAL_TYPE_CHI",
    "XMODEL1_SPECIAL_TYPE_CHI_LOW",
    "XMODEL1_SPECIAL_TYPE_CHI_MID",
    "XMODEL1_SPECIAL_TYPE_CHI_HIGH",
    "XMODEL1_SPECIAL_TYPE_KAN",
    "XMODEL1_SPECIAL_TYPE_PON",
    "XMODEL1_SPECIAL_TYPE_DAIMINKAN",
    "XMODEL1_SPECIAL_TYPE_ANKAN",
    "XMODEL1_SPECIAL_TYPE_KAKAN",
    "XMODEL1_SPECIAL_TYPE_RYUKYOKU",
    "XMODEL1_SPECIAL_TYPE_NONE",
    "XMODEL1_CHI_SPECIAL_TYPES",
    "XMODEL1_KAN_SPECIAL_TYPES",
    "XMODEL1_SPECIAL_TYPE_NAMES",
]
